/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks that the BFF is up */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check_apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks that the upstream APIs are reachable */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every upstream API is reachable */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckApisResponse"];
                    };
                };
                /** @description At least one upstream API is unreachable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckApisResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Core profile, sessions, preferences and notification settings of the signed-in user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsBootstrap"];
                    };
                };
                /** @description Invalid session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Profile unavailable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsProfilePatch"];
                };
            };
            responses: {
                /** @description Profile saved, then read again */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsProfile"];
                    };
                };
                /** @description Invalid or unsupported fields, or a changed `email` without `current_password` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `email` sent with a wrong `current_password`, or an account without password */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `email` is already used by another account */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is unavailable, failed or answered an unexpected status */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/settings/appearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsAppearancePatch"];
                };
            };
            responses: {
                /** @description appearance settings saved by Core */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsAppearance"];
                    };
                };
                /** @description Invalid or unsupported fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is unavailable, failed or answered an unexpected status */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/settings/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsGeneralPatch"];
                };
            };
            responses: {
                /** @description general settings saved by Core */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsGeneral"];
                    };
                };
                /** @description Invalid or unsupported fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is unavailable, failed or answered an unexpected status */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsNotificationsPatch"];
                };
            };
            responses: {
                /** @description notifications settings saved by Core */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsNotifications"];
                    };
                };
                /** @description Invalid or unsupported fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is unavailable, failed or answered an unexpected status */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Core is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "UNPROCESSABLE_ENTITY" | "TOO_MANY_REQUESTS" | "INTERNAL_ERROR" | "BAD_GATEWAY" | "SERVICE_UNAVAILABLE" | "GATEWAY_TIMEOUT";
                message: string;
                details: {
                    path?: string;
                    message: string;
                }[];
            };
        };
        CheckApisResponse: {
            /** @enum {string} */
            status: "OK" | "Error";
            /** @enum {string} */
            core_api: "Connected" | "Unreachable";
        };
        SettingsProfile: {
            /** @example Security */
            first_name: string;
            /** @example Admin */
            last_name: string;
            /**
             * Format: email
             * @example security-admin@mairie360.fr
             */
            email: string;
            /** @example 0612345678 */
            phone?: string | null;
        };
        SettingsProfilePatch: {
            /** @example Security */
            first_name?: string;
            /** @example Admin */
            last_name?: string;
            /**
             * Format: email
             * @example security-admin@mairie360.fr
             */
            email?: string;
            /** @example 0612345678 */
            phone?: string | null;
            /**
             * @description Current password of the account, required when `email` changes the current address
             * @example current-password
             */
            current_password?: string;
        };
        SettingsAppearance: {
            /**
             * @example dark
             * @enum {string|null}
             */
            theme: "light" | "dark" | "system" | null;
            /** @example Marianne */
            font_family: string | null;
            /** @example 16 */
            font_size: number | null;
            /** @example compact */
            density: string | null;
        };
        SettingsAppearancePatch: {
            /**
             * @example dark
             * @enum {string|null}
             */
            theme?: "light" | "dark" | "system" | null;
            /** @example Marianne */
            font_family?: string | null;
            /** @example 16 */
            font_size?: number | null;
            /**
             * @example compact
             * @enum {string|null}
             */
            density?: "compact" | "normal" | "comfortable" | null;
        };
        SettingsGeneral: {
            /** @example fr */
            language: string | null;
            /** @example Europe/Paris */
            timezone: string | null;
            /** @example DD/MM/YYYY */
            date_format: string | null;
            /** @example /dashboard */
            home_page: string | null;
            /** @example false */
            auto_open_notifications: boolean | null;
        };
        SettingsGeneralPatch: {
            /** @example fr */
            language?: string | null;
            /** @example Europe/Paris */
            timezone?: string | null;
            /**
             * @example DD/MM/YYYY
             * @enum {string|null}
             */
            date_format?: "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD" | null;
            /** @example /dashboard */
            home_page?: string | null;
            /** @example false */
            auto_open_notifications?: boolean | null;
        };
        SettingsNotifications: {
            /** @example true */
            email: boolean | null;
            /** @example false */
            push: boolean | null;
            /** @example true */
            desktop: boolean | null;
            /** @example true */
            messages: boolean | null;
            /** @example true */
            projects: boolean | null;
            /** @example false */
            calendar: boolean | null;
        };
        SettingsNotificationsPatch: {
            /** @example true */
            email?: boolean | null;
            /** @example false */
            push?: boolean | null;
            /** @example true */
            desktop?: boolean | null;
            /** @example true */
            messages?: boolean | null;
            /** @example true */
            projects?: boolean | null;
            /** @example false */
            calendar?: boolean | null;
        };
        SettingsBootstrap: {
            profile: components["schemas"]["SettingsProfile"];
            sessions: {
                id: string;
                device_info: string;
                ip_address: string;
                created_at: string;
                expires_at: string;
                revoked_at?: string | null;
            }[];
            appearance: components["schemas"]["SettingsAppearance"] | null;
            general: components["schemas"]["SettingsGeneral"] | null;
            notifications: components["schemas"]["SettingsNotifications"] | null;
            sources: {
                /** @enum {string} */
                sessions: "available" | "unavailable";
                /** @enum {string} */
                preferences: "available" | "unavailable";
                /** @enum {string} */
                notifications: "available" | "unavailable";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
